title = "Project Gitleaks Config"

[extend]
useDefault = true

[allowlist]
# Ignore findings only inside build.gradle
files = ["build.gradle"]

# Required dummy regex to satisfy Gitleaks schema
regexes = [
  '''^$'''  # matches nothing, keeps config valid
]
